baseURL = "https://blog.zachpovey.dev"
languageCode = "en-uk"
title = "Zach's Blog"
copyright = "Feel free to share, use, or adapt any content from this blog - a shout out would be nice!"
theme = "npqhugo"
pygmentsUseClasses=true

[params]
  author = "Zach Povey"
  description = "Zach Povery's blog about technology; programming in python, typescript and go; and life."
  keywords = "blog technology python typescript go data engineering software engineering zach zachary povey"
  useAvatar = true
  microBlogSection = "micro_posts"
  displayMicroBlog = true
  displayRecent = true
  displayHomeContent = true
  recentMax = 4
  # mail = "zach@zachpovey.dev"
  # phone = "8888888888"
  # formspreeID = "yourformspreeID"

[menu]
  [[menu.main]]
    name = "home"
    pre = '<i class="hn hn-home"></i>'
    url = "/"
    weight = -9 
  [[menu.main]]
    name = "blog"
    pre = '<i class="hn hn-clipboard"></i>'
    url = "/blog/"
    weight = -8
  [[menu.main]]
    name = "tags"
    pre = '<i class="hn hn-tag"></i>'
    url = "/tags"
    weight = -7 
  [[menu.main]]
    name = "github"
    pre = '<i class="hn hn-github"></i>'
    url = "https://github.com/zachary-povey"
    weight = -6 
  [[menu.main]]
    name = "RSS"
    pre = '<i class="hn hn-rss"></i>'
    url = "/index.xml"
    weight = -4 
  [[menu.main]]
    name = "cv island"
    pre = '<i class="hn hn-plane"></i>'
    url = "https://zachpovey.dev"
    weight = -1 

[taxonomies]
tag = "tags"